apiVersion: v1
kind: Service
metadata:
  name: travel-website-service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: travel-website
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
